# Generated by Django 3.1.3 on 2021-03-09 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='name',
            field=models.CharField(default='codingal', max_length=255),
            preserve_default=False,
        ),
    ]
